CREATE USER DESAFIO_VOTACAO IDENTIFIED BY oracle;

GRANT CONNECT TO DESAFIO_VOTACAO;

GRANT CONNECT, RESOURCE, DBA TO DESAFIO_VOTACAO;

GRANT DBA TO DESAFIO_VOTACAO;

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO DESAFIO_VOTACAO;

GRANT UNLIMITED TABLESPACE TO DESAFIO_VOTACAO;

GRANT CREATE MATERIALIZED VIEW TO DESAFIO_VOTACAO;

GRANT CREATE TABLE TO DESAFIO_VOTACAO;

GRANT GLOBAL QUERY REWRITE TO DESAFIO_VOTACAO;

GRANT SELECT ANY TABLE TO DESAFIO_VOTACAO;