CREATE TABLE ASSOCIADO(
ID_ASSOCIADO 	NUMBER PRIMARY KEY NOT NULL,
NOME 			VARCHAR2(50) NOT NULL ,
CPF 			VARCHAR2(11) NOT NULL
);

CREATE SEQUENCE seq_associado
	START WITH 1
	INCREMENT BY 1
 	NOCACHE
	NOCYCLE;

CREATE TABLE PAUTA (
ID_PAUTA 		NUMBER PRIMARY KEY NOT NULL,
TITULO 			VARCHAR2(120) NOT NULL,
DESCRICAO 		VARCHAR2(200) NOT NULL,
DATA_CRIACAO 	DATE NOT NULL
);

CREATE SEQUENCE seq_pauta
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE TABLE SESSAO_VOTACAO (
    ID_SESSAO_VOTOS      NUMBER PRIMARY KEY NOT NULL,
    DATA_INICIO_VOTACAO  TIMESTAMP NOT NULL,
    DATA_TERMINO_VOTACAO TIMESTAMP NOT NULL,
    STATUS_VOTACAO       VARCHAR2(20) NOT NULL,
    ID_PAUTA             NUMBER NOT NULL,
CONSTRAINT FK_SESSAO_PAUTA FOREIGN KEY (ID_PAUTA) REFERENCES PAUTA (ID_PAUTA)
);

CREATE SEQUENCE SEQ_SESSAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE VOTO (
    ID_VOTO          NUMBER PRIMARY KEY NOT NULL,
    TIPO_VOTO        VARCHAR2(20) NOT NULL,
    DATA_CRIACAO     TIMESTAMP NOT NULL,
    ID_ASSOCIADO     NUMBER NOT NULL,
    ID_SESSAO_VOTOS  NUMBER NOT NULL,
CONSTRAINT FK_VOTO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO) REFERENCES ASSOCIADO (ID_ASSOCIADO),
CONSTRAINT FK_VOTO_SESSAO FOREIGN KEY (ID_SESSAO_VOTOS) REFERENCES SESSAO_VOTACAO (ID_SESSAO_VOTOS)
);

CREATE SEQUENCE SEQ_VOTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;





