server:
  port: 8081

spring:
  application:
    group: desafio-tecnico
    name: desafio-votacao

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

logging:
  level:
    root: INFO
    org.springframework: INFO